---
- name: Create Ansible folder
  hosts: all
  become: true

  tasks:
    - name: Create ansible directory
      command: mkdir /home/ubuntu/ansible
    - name: Create another directory
      command: mkdir /home/ubuntu/ansible/another
